// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 0.8.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nutrilab.Web.App.Shared.Models
{

  public partial class PatientReportModel
  {

    public Guid Id { get; set; }

    public Guid PatientId { get; set; }

    public DateTime CreatedAt { get; set; }

    [Editable(true)]
    [Required]
    [Range(1, 500)]
    public double WeightKg { get; set; }

    [Editable(true)]
    [Required]
    [Range(20, 300)]
    public double HeightCm { get; set; }

    public PatientVentialtionParametersModel Ventilation { get; set; }

    public ICollection<EnergyEquationReportItem> Equations { get; set; }
  }
}
