// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 0.8.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

namespace Nutrilab.Web.App.Shared.Models
{

  public partial class PatientVentialtionParametersModel
  {

    [Editable(true)]
    [Required]
    [Range(1, 100)]
    public double VentilationLMin { get; set; }

    [Editable(true)]
    [Required]
    [Range(20, 60)]
    public double TemperatureMaxC { get; set; }
  }
}
